app/chatapp/main/forms.py
from flask_wtf import FlaskForm
from wtforms.fields import StringField, SubmitField
from wtforms.validators import DataRequired


class LoginForm(FlaskForm):
    """Accepts a nickname and a room."""
    name = StringField('Name', validators=[DataRequired()])
    room = StringField('Room', validators=[DataRequired()])
    submit = SubmitField('Enter Chatroom')

class NewConversation(FlaskForm):
    """Accepts a username to start a new conversation with"""
    username = StringField('Username', validators=[DataRequired()])
    submit = SubmitField('Start Conversation')

app/chatapp/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import routes, events

app/chatapp/main/routes.py
from flask import session, redirect, url_for, render_template, request
from . import main
from .forms import LoginForm, NewConversation
from .databasee import getConversation, getChatrooms

@main.route('/', methods=['GET', 'POST'])
def index():
    """Login form to enter a room."""
    form = LoginForm()
    if form.validate_on_submit():
        session['name'] = form.name.data
        # session['room'] = form.room.data
        return redirect(url_for('.myconversations'))
    elif request.method == 'GET':
        form.name.data = session.get('name', '')
    return render_template('index.html', form=form)

@main.route('/chat')
def chat():
    """Chat room. The user's name and room must be stored in
    the session."""
    active_chatroom = request.args.get('active_chatroom')
    session['active_chatroom'] = active_chatroom
    name = session.get('name', '')
    room = session.get('room', '')

    # populate the messages from the database
    messages = []
    for message in getConversation(active_chatroom):
        messages.append(message["from"] + ": " + message["message"])

    return render_template('chat.html', name=name, room=room, messages=messages, active_chatroom=active_chatroom)


@main.route('/myconversations')
def myconversations():
    """Conversations. This page contains the lisut of conversations
    the user has had with other users"""
    # get the conversations from the database
    name = session.get('name', '')
    chatrooms = getChatrooms(name)
    return render_template('myconversations.html', chatrooms=chatrooms, name=name)

@main.route('/new_conversation')
def new_conversation():
    """New conversation. This page allows the user to start a new
    conversation with another user"""
    form = NewConversation()
    if form.validate_on_submit():
        session['targetUsername'] = form.username.data
        return redirect(url_for('.myconversations'))
    elif request.method == 'GET':
        form.username.data = session.get('username', '')
    
    return render_template('new_conversation.html', form=form)
    

app/chatapp/templates/chat.html
<html>
    <head>
        <title>Flask-SocketIO-Chat: {{ room }}</title>
        <script type="text/javascript" src="//code.jquery.com/jquery-1.4.2.min.js"></script>
        <script type="text/javascript" src="//cdn.socket.io/4.4.1/socket.io.min.js"></script>
        <script type="text/javascript" charset="utf-8">
            var socket;
            $(document).ready(function(){
                socket = io.connect('http://' + document.domain + ':' + location.port + '/chat');
                socket.on('connect', function() {
                    socket.emit('joined', {});
                });
                socket.on('status', function(data) {
                    $('#chat').val($('#chat').val() + '<' + data.msg + '>\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                socket.on('message', function(data) {
                    $('#chat').val($('#chat').val() + data.msg + '\n');
                    $('#chat').scrollTop($('#chat')[0].scrollHeight);
                });
                $('#text').keypress(function(e) {
                    var code = e.keyCode || e.which;
                    if (code == 13) {
                        // get the value
                        text = $('#text').val();
                        // clear the value
                        $('#text').val('');
                        socket.emit('text', {msg: text});
                    }
                });
            });
            function leave_room() {
                socket.emit('left', {}, function() {
                    socket.disconnect();

                    // go back to the login page
                    window.location.href = "{{ url_for('main.myconversations') }}";
                });
            }
        </script>
    </head>
    <body>
        <h1>Flask-SocketIO-Chat: {{ room }}</h1>

        <textarea id="chat" cols="80" rows="20">
            {% for message in messages %}
            {{ message }}
            {% endfor %}
        </textarea><br><br>
        <input id="text" size="80" placeholder="Enter your message here"><br><br>
        <a href="#" onclick="leave_room();">Leave this room</a>
    </body>
</html>

app/chatapp/templates/index.html
<html>
    <head>
        <title>Flask-SocketIO-Chat</title>
    </head>
    <body>
        <h1>Flask-SocketIO-Chat</h1>
        <form method="POST">
            {{ form.hidden_tag() }}
            {{ form.name.label }}: {{ form.name() }} {% for error in form.name.errors %}{{ error }}{% endfor %}<br>
            {{ form.room.label }}: {{ form.room() }} {% for error in form.room.errors %}{{ error }}{% endfor %}<br>
            {{ form.submit() }}
        </form>
    </body>
</html>

app/chatapp/templates/myconversations.html
<html>
    <head>
        <h1>{{name}}'s Conversations</h1>
    </head>
    <body>
        <ul>
            {% for chatroom in chatrooms %}
                <li><a href="{{ url_for('main.chat', active_chatroom=chatroom['chatroom_id']) }}">{{ chatroom['chatroom_name'] }}</a></li>
            {% endfor %}
        </ul>
        <br><br>
        <!-- start a new conversation -->
        <a href="{{ url_for('main.new_conversation') }}">Start a new conversation</a>
    </body>
</html>

app/chatapp/templates/new_conversation.html
<html>
    <h1>New Conversation</h1>
    <form method="POST">
        {{ form.hidden_tag() }}
        {{ form.username.label }}: {{ form.username() }} {% for error in form.username.errors %}{{ error }}{% endfor %}<br>
        {{ form.submit() }}
    </form>
</html>